require "digest"
require "fileutils"
require "open-uri"
require "tmpdir"

# Vendors libcurl-impersonate's static archive + headers for each supported
# platform under ext/curl_impersonate/vendor/<ruby_platform>/. The directory
# layout matches what extconf.rb's configure_from_dir() expects:
#
#   ext/curl_impersonate/vendor/<ruby_platform>/
#     lib/libcurl-impersonate.a
#     lib/libngtcp2_crypto_ossl.a
#     include/curl-impersonate/curl_impersonate.h
#
# When rake-compiler cross-compiles for a given platform, extconf.rb finds
# this directory first (before falling back to pkg-config) and links the
# vendored .a directly into the resulting native gem.
#
# Upstream release URLs are stable and pinned with SHA256 below — update
# CURL_IMPERSONATE_VERSION + checksums together when bumping.

CURL_IMPERSONATE_VERSION = "1.5.1".freeze

# Maps Ruby platform triple (as understood by rake-compiler) → lexiforest
# release asset suffix + SHA256. The Ruby triple is what shows up in the
# .gem filename and in RUBY_PLATFORM on the target system.
CURL_IMPERSONATE_PLATFORMS = {
  "arm64-darwin"   => { asset: "arm64-macos",        sha256: "c78ac9f0772ff806c7196764b57fc4fab426e95cf7d64fd9f3334e25b998c551" },
  "x86_64-darwin"  => { asset: "x86_64-macos",       sha256: "a744c0f7b6e9ab9aa0a436134e062a9bf56c9293832ac01c63b5ea751fb0209d" },
  "aarch64-linux"  => { asset: "aarch64-linux-gnu",  sha256: "3bcaeeca0428fe379f6c6e44b18cf09fec0e940260ff66f6be8334a08f69b139" },
  "x86_64-linux"   => { asset: "x86_64-linux-gnu",   sha256: "f5da4e08253ff8aa0a51ee5ce6ee0c169b46f88f2285d8351ce674f88a6aa4bc" },
}.freeze

VENDOR_ROOT = File.expand_path("../ext/curl_impersonate/vendor", __dir__)

# The header file is the same across all platforms — generated by the brew
# formula. We embed it verbatim so the source gem and every precompiled gem
# include it even though the upstream tarball does not.
CURL_IMPERSONATE_H = <<~HEADER.freeze
  #ifndef CURL_IMPERSONATE_H
  #define CURL_IMPERSONATE_H

  #include <curl/curl.h>

  #ifdef __cplusplus
  extern "C" {
  #endif

  CURLcode curl_easy_impersonate(CURL *curl, const char *target, int default_headers);

  #ifdef __cplusplus
  }
  #endif

  #endif /* CURL_IMPERSONATE_H */
HEADER

def upstream_url(asset)
  "https://github.com/lexiforest/curl-impersonate/releases/download/v#{CURL_IMPERSONATE_VERSION}/libcurl-impersonate-v#{CURL_IMPERSONATE_VERSION}.#{asset}.tar.gz"
end

def vendor_dir_for(ruby_platform)
  File.join(VENDOR_ROOT, ruby_platform)
end

def download_and_extract(ruby_platform, info)
  dest = vendor_dir_for(ruby_platform)
  url = upstream_url(info[:asset])

  if File.exist?(File.join(dest, "lib", "libcurl-impersonate.a"))
    puts "[vendor:#{ruby_platform}] already present at #{dest}"
    return
  end

  puts "[vendor:#{ruby_platform}] downloading #{url}"
  Dir.mktmpdir do |tmp|
    tarball = File.join(tmp, "upstream.tar.gz")
    URI.open(url) { |io| File.binwrite(tarball, io.read) }

    actual = Digest::SHA256.file(tarball).hexdigest
    unless actual == info[:sha256]
      raise "checksum mismatch for #{url}\n  expected: #{info[:sha256]}\n  actual:   #{actual}"
    end

    FileUtils.mkdir_p(File.join(dest, "lib"))
    FileUtils.mkdir_p(File.join(dest, "include", "curl-impersonate"))

    sh "tar", "xzf", tarball, "-C", File.join(dest, "lib")

    File.write(
      File.join(dest, "include", "curl-impersonate", "curl_impersonate.h"),
      CURL_IMPERSONATE_H,
    )
  end
  puts "[vendor:#{ruby_platform}] ready at #{dest}"
end

namespace :vendor do
  CURL_IMPERSONATE_PLATFORMS.each do |ruby_platform, info|
    desc "Download and extract libcurl-impersonate #{CURL_IMPERSONATE_VERSION} for #{ruby_platform}"
    task ruby_platform.to_sym do
      download_and_extract(ruby_platform, info)
    end
  end

  desc "Download libcurl-impersonate for every supported platform"
  task all: CURL_IMPERSONATE_PLATFORMS.keys.map(&:to_sym)

  desc "Remove every vendored archive"
  task :clean do
    FileUtils.rm_rf(VENDOR_ROOT)
    puts "[vendor:clean] removed #{VENDOR_ROOT}"
  end
end
